#! /bin/sh


#-----------------------AUTOSTART------------------------#
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh


#----------------------MONITORS--------------------------#

external_monitor=$(xrandr --query | grep 'DP-1')
if [[ $external_monitor = *connected* ]]; then
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d    
else
bspc monitor eDP-1 -d 
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
fi
#-------------------------VISUAL-------------------------#


#Borders & Gaps
bspc config border_width        1 
bspc config window_gap          30

bspc config normal_border_color 	\#565f61     #uf window
bspc config active_border_color		\#ffffff     #f window uf monitor
bspc config focused_border_color	\#c9eaf0     #f window

#Focus 
bspc config focus_follows_pointer 	false

#Split Ratio
bspc config split_ratio          0.60

#Monocle
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
 

#-----------------------SCRATCHPADS-------------------#

