#!/bin/sh
# vim:foldmethod=marker

#-----------------------------SUPERIOR BSPWMRC---------------------------------



# AUTOSTART--------------------------------------------------------{{{1

pgrep -x sxhkd > /dev/null || sxhkd &   # Start sxhkd

nitrogen --restore &                    # Restore wallpaper
$HOME/.config/polybar/launch.sh         # Launch status bar
kmix
nm-applet


# VISUAL-----------------------------------------------------------{{{1

bspc config split_ratio          0.60   # Window split ratio


    # BORDERS & GAPS-----------------------------------------------{{{2

    bspc config window_gap          25  # Gaps
    bspc config border_width        0   # Borders 

    bspc config normal_border_color 	\#33322e    # UF window color
    bspc config active_border_color 	\#ffffff    # F window, UF monitor color
    bspc config focused_border_color	\#c9eaf0    # Focused window color
    bspc config presel_feedback_color   \#ffffff    # Preselect box color


    # FOCUS--------------------------------------------------------{{{2 

    bspc config focus_follows_pointer 	false   # Free the mouse


    # MONOCLE------------------------------------------------------{{{2

    bspc config borderless_monocle   true    # Remove the borders from monocle
    bspc config gapless_monocle      true    # Remove the gaps from monocle
    bspc config top_monocle_padding  -25     # Some padding to cover the status bar


    # RULES--------------------------------------------------------{{{2

    bspc rule -a Gimp desktop='^8' state=floating follow=on     # Manage Gimp
    bspc rule -a Screenkey manage=off   # Screen key display

     
    # }}}


# MONITORS---------------------------------------------------------{{{1

#If a second monitor is connected make it the main one 

external_monitor=$(xrandr --query | grep 'DP-1')
if [[ $external_monitor = *disconnected* ]]; then
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d    
else
bspc monitor eDP-1 -d 
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
fi


