#! /bin/sh
# vim:foldmethod=marker

#-----------------------------SUPERIOR BSPWMRC---------------------------------





# AUTOSTART--------------------------------------------------------{{{1

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh


# MONITORS---------------------------------------------------------{{{1

external_monitor=$(xrandr --query | grep 'DP-1')
if [[ $external_monitor = *connected* ]]; then
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-1 -d    
else
bspc monitor eDP-1 -d 
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
fi

# VISUAL-----------------------------------------------------------{{{1


    # BORDERS & GAPS-----------------------------------------------{{{2

    bspc config border_width        1 
    bspc config window_gap          30
    bspc config normal_border_color 	\#33322e     #uf window
    bspc config active_border_color 	\#ffffff  #f window uf monitor
    bspc config focused_border_color	\#c9eaf0     #f window

    # FOCUS--------------------------------------------------------{{{2 

    bspc config focus_follows_pointer 	false

    # SPLIT RATIO--------------------------------------------------{{{2

    bspc config split_ratio          0.60

    # MONOCLE------------------------------------------------------{{{2

    bspc config borderless_monocle   true
    bspc config gapless_monocle      true

    # RULES--------------------------------------------------------{{{2

    bspc rule -a Gimp desktop='^8' state=floating follow=on
    bspc rule -a Kupfer.py focus=on
    bspc rule -a Screenkey manage=off
     
    # }}}


